import "./scss/app.scss";
import { Header } from "./components/Header";
import type { Metadata } from "next";

import { Roboto } from "next/font/google";
import { ReduxProvider } from "./redux/provider";
import Footer from "./components/Footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ugmonk",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}

export default RootLayout;
